version: "3"

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 5000:3000
    environment:
      MONGO_URI: mongodb://mongo_db:27017/music-app?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.15
      NODE_ENV: production

    depends_on:
      - mongo_db

volumes: mongo_db:{}
